adding a few more custom css options too the documentation
ajnart/homarr-docs pull request #32
Opened 2023-01-29 17:47 UTC by blassley

*Thank you for contributing to Homarr! So that your Pull Request can be handled effectively, please populate the following fields (delete sections that are not applicable)*

### Category
documentation

### Overview
adding blur and border custom css

2023-01-29 20:15 UTC, manuel-rw commented
Thank you for your contribution, but can you please stop opening new pull requests the entire time?
You opened already 4 with the same content. Please do not open more!
Please mention me when you're done and this can be reviewed.

2023-01-29 21:05 UTC, blassley commented
> Thank you for your contribution, but can you please stop opening new pull requests the entire time?
> 
> You opened already 4 with the same content. Please do not open more!
> 
> Please mention me when you're done and this can be reviewed.

Yes of course I'm not sure if this was due to connection issue earlier or what but visual code kept failing then I looked on GitHub and they were all here lol take a look at this when you have time

2023-01-31 16:28 UTC, manuel-rw requested changes
Almost good to go. Thank you for your work!

2023-01-31 16:28 UTC, manuel-rw commented on docs/customizations/custom-css.md
> +.mantine-w4dwz9 {
Can you mention, that these class names will change each time Homarr is updated?
Also, you could create a ticket for this, so we crate unused static class names, so they don't change anymore.

2023-02-03 17:44 UTC, merged

2023-02-03 17:44 UTC, manuel-rw commented
Thanks for the contribution!