docs: add qbittorent csrf known issue
ajnart/homarr-docs pull request #33
Opened 2023-01-31 11:23 UTC by adriencarbonaro

### Category
Documentation

### Overview
Added the qBittorrent CSRF Unauthorized screen known issue.

### Issue Number
[#600](https://github.com/ajnart/homarr/issues/600)
[#285](https://github.com/ajnart/homarr/issues/285)
[#140](https://github.com/ajnart/homarr/issues/140)

2023-01-31 16:31 UTC, manuel-rw requested changes
Thank you for your work! We can merge after these requested changes

2023-01-31 16:31 UTC, manuel-rw commented on docs/community/known-issues.md
> +- Uncheck [__Enable Cross-Site Request Forgery (CSRF) protection__](./img/qbittorrent_options_csrf.png).
Can you wrap this in a details object?
This way, we could display the image directly instead of linking to it.
It would also avoid cluttering the page with images :)

https://docusaurus.io/docs/markdown-features#details

2023-02-07 10:47 UTC, manuel-rw requested changes
Check out the preview from Vercel - the pictures don't display

2023-02-07 11:25 UTC, adriencarbonaro commented
It seems the `img` tag inside detail object cannot receive image from outside the `static` directory (or url).
Maybe I'm missing something ?
Can I put the images inside this directory or do we prefer to remove the images ? I think the unauthorized picture is not mandatory but the settings one is quite useful.

2023-02-18 17:11 UTC, walkxcode commented on docs/community/known-issues.md
> +  <img src="./img/qbittorrent_unauthorized.png"/>
```suggestion
<>

	![](img/qbittorrent_unauthorized.png)

<>
```

This should work. **(I have not tested this)**

2023-02-19 17:48 UTC, adriencarbonaro commented on docs/community/known-issues.md
> +  <img src="./img/qbittorrent_unauthorized.png"/>
Hi @walkxcode , thanks for the suggestion. Unfortunately, it does not seem to work.

2023-02-25 19:37 UTC, manuel-rw commented
@adriencarbonaro can you fix the build?

2023-02-25 19:39 UTC, adriencarbonaro commented
I'm waiting for an answer on my comment first. I need to know if i can move the images

2023-02-25 19:41 UTC, manuel-rw commented
Having 1-2 empty lines before and after the ``![]()`` does not work?

2023-02-25 20:54 UTC, merged

2023-02-25 20:54 UTC, manuel-rw commented
Thanks for the contribution :)

2023-02-25 21:03 UTC, adriencarbonaro commented
Oups, a typo was introduced when fixing the image issue. The 2 photos are the same. The first one should be `qbittorrent_unauthorized.png`