Update board-customization.mdx
ajnart/homarr-docs pull request #98
Opened 2023-11-15 01:26 UTC by No-Maines-Land

*Thank you for contributing to Homarr! So that your Pull Request can be handled effectively, please populate the following fields (delete sections that are not applicable)*

### Category
> Documentation

### Overview
> Added explanation for filtering unsplash based on resolution.

### Issue Number _(if applicable)_
> Related issue: triggered by discord question: https://discord.com/channels/972958686051962910/1174146709908095016

### New Vars _(if applicable)_

### Screenshot _(if applicable)_

2023-11-21 18:53 UTC, manuel-rw commented on docs/customizations/board-customization.mdx
> +Resultions can be filtered to better match your dashboard size by ending with the resolution `https://source.unsplash.com/featured/1920x1080`
Do you mean ``Resolutions``?

2023-11-21 19:06 UTC, No-Maines-Land commented on docs/customizations/board-customization.mdx
> +Resultions can be filtered to better match your dashboard size by ending with the resolution `https://source.unsplash.com/featured/1920x1080`
Yes. Spelling is hard.

2023-12-02 17:01 UTC, manuel-rw requested changes

2023-12-30 21:07 UTC, manuel-rw commented
> [!CAUTION]
> Hello 👋.
> This is an **automated message**. This repository has <b>moved to https://github.com/homarr-labs/documentation</b> and > further contributions to this repository will be declined.
> Please **_move your issue / pull request to our new repository_**.
> We are making this change to take advantage of GitHub's organizations feature.
> We apologize for the inconvenience.

2023-12-30 21:07 UTC, closed without merging